### ISSUE TITLE
Option to use a preset familiar

### ISSUE THREAD

**Issue by Aeresx** [taltamir/ttpack#11]
Add a switch to not use the autoscend familiar switching and just the one that is present. I rather use my puckman to farm powerpills than auto logic switching to hand turky

**Comment by taltamir** [comment]
change made.
there is a new setting called `guzzlr_autoFamiliar` and it will only switch familiars if it is set to true (default value is true).
set it to false and it will instead leave your familiar alone. you will need to set familiar ahead of time.

**Comment by taltamir** [comment]
more changes.
`guzzlr_manualFamiliar` can be set to true if you want to manually specify a familiar name to switch to.
`guzzlr_manualFamiliarChoice` is where you set the name of the familiar
