### ISSUE TITLE
You need to equip your Personal Ventilation Unit

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#22]
In a perfect world the script would make an outfit checkpoint, equip the unit while not displacing any Guzzlr gear,, complete the delivery and then restore the original outfit.

`Visit to Conspiracy Island: The Secret Government Laboratory in progress...
You need to equip your Personal Ventilation Unit.

Failed to adventure in [The Secret Government Laboratory]
Stack trace:
  at guzzlr_deliverLoop (guzzlr.ash:684)
  at guzzlr_deliver (guzzlr.ash:702)
  at guzzlr_aftercore (guzzlr.ash:719)
  at main (guzzlr.ash:770)
printStackOnAbort => false
breakableHandling => 1
choiceAdventureScript => scripts\CounterChecker.ash
promptAboutCrafting => 1`

**Comment by taltamir** [comment]
hypothetically fixed with 8206784ff7f913f8b6c1e5fbcd53dc6c62a00839

Please let me know if this fixed it or not

**Comment by magus-prime** [comment]
I'm running a Platinum delivery every day so it should come up eventually.
