### ISSUE TITLE
Pirates zone access issue not fixed

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#26]
WIth Mafia r20195 the script tried to do a delivery in Belowdecks.  I tried the new option to allowPirateQuest and it failed with the following:

`> set guzzlr_allowPirateQuest = true

guzzlr_allowPirateQuest     => true

> guzzlr 50

printStackOnAbort     => true
promptAboutCrafting => 0
breakableHandling => 4
choiceAdventureScript     => scripts/autoscend/auto_choice_adv.ash
currentMood => apathetic
[INFO]     - Findin' the Cap'n
[INFO] - Equipping     eyepatch to slot hat
[INFO] - Equipping     swashbuckling pants to slot pants
[INFO] -     Equipping stuffed shoulder parrot to slot acc3
nextAdventure =>     Barrrney's Barrr

Restoring HP! Currently at     1214 of 2694 HP, 172 of 1781 MP, current meat: 902726766 ... Target HP =     2560.
Restoring MP! Currently at 1214 of     2694 HP, 172 of 1781 MP, current meat: 902726766 ... Target MP = 373.
Get     thee to a nunnery!
You gain 1,000 hit points
You gain 1,000 Mojo     Points
Casting Cannelloni Cocoon 1 times...
You gain 480 hit points
Cannelloni     Cocoon was successfully cast.

Visit to Island: Barrrney's Barrr in     progress...
You can't get to that area.

[INFO]     - Findin' the Cap'n
[INFO] - Equipping     eyepatch to slot hat
[INFO] - Equipping     swashbuckling pants to slot pants
[INFO] -     Equipping stuffed shoulder parrot to slot acc3

Visit to     Island: Barrrney's Barrr in progress...
You can't get     to that area.

[INFO] - Findin' the Cap'n
[INFO]     - Equipping eyepatch to slot hat
[INFO] -     Equipping swashbuckling pants to slot pants
[INFO]     - Equipping stuffed shoulder parrot to slot acc3`

This is in aftercore and all parts of the Swashbuckling Getup are in inventory.  After manually equiping the outfit I reran the script and it was able to adventure in the Barr and got the the Captain.

The script then got the map to the crab and the treasure but then maximized for Guzzlr deliveries.  That unequipped the Swashbuckling Getup which made it impossible to adventure in the Barr to continue with the quest to open the F'csle.

At this point there there aren't enough insults to continue even if wearing the outfit.  Only a 7.4% chance.

Here's the session log:  
[Arbos_20200618.txt](https://github.com/taltamir/ttpack/files/4798260/Arbos_20200618.txt)

_Originally posted by @magus-prime in https://github.com/taltamir/ttpack/issues/7#issuecomment-645958351_

**Comment by taltamir** [comment]
well that is odd. i had it work for me the other day. I will look through the log and code to try to pinpoint the issue

**Comment by taltamir** [comment]
I think i figured it out. its the pants. guzzlr pants are breaking your pirate outfit which prevent you from adventuring there.

**Comment by taltamir** [comment]
Tried another fix 98c586a592f2eb8efabe5690a023d9f6fdc1f18b
please let me know if it solved the problem

**Comment by magus-prime** [comment]
Will do but it may have been only part of the problem.  In this instance the zone needed for the delivery was Belowdecks.  The script shifted to "delivery mode" before that zone was open.

**Comment by taltamir** [comment]
> Will do but it may have been only part of the problem. In this instance the zone needed for the delivery was Belowdecks. The script shifted to "delivery mode" before that zone was open.

According to the log you posted the script was failing by trying to adventure in barr to find the captain

**Comment by magus-prime** [comment]
What I meant was that the logic of the script equipped Guzzlr clothing even though there were many more steps required to open the zone where it would be helpful.

Only once Belowdecks is open is the Guzzlr clothing helpful.  Since the script runs a custom maximizer string before every adventure this, potential, issue may be mitigated.

**Comment by taltamir** [comment]
> What I meant was that the logic of the script equipped Guzzlr clothing even though there were many more steps required to open the zone where it would be helpful.
> 
> Only once Belowdecks is open is the Guzzlr clothing helpful. Since the script runs a custom maximizer string before every adventure this, potential, issue may be mitigated.

Thank you. but just to clarify the logic was already set to only equip guzzlr clothing only after you unlocked the location. It just incorrectly thought it was unlocked due to some upstream weirdness that I was not accounting for. This should be fixed now

**Comment by magus-prime** [comment]
In a weird way the script just demonstrated that it can, at least, get the Pirate Fledges.  I think we can call this fixed.

**Comment by taltamir** [comment]
Thanks for letting me know.
