### ISSUE TITLE
Don't try to buy day passes if the airport item of the month is owned

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#3]
I just took a look at the script and it assumes that a day pass is required for all platinum deliveries. Wouldn't it be straight-forward to check whether the following are set to "false" before trying to buy a day pass?

```
coldAirportAlways
hotAirportAlways
sleazeAirportAlways
spookyAirportAlways
stenchAirportAlways
```

**Comment by taltamir** [comment]
I actually was checking those values. I was just doing it wrong. my bad there. Couldn't really do too much testing on plat quests due to the 1/day limit.

I pushed a fix. please try it with `svn update` and let me know if it solved the issue

**Comment by magus-prime** [comment]
Your change to the logic did the trick.  The script, successfully performed a platinum and three gold deliveries.  Thank you.
