### ISSUE TITLE
Incomplete cleanup when script aborts

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#33]
I've had it happen a few times where, when the script aborts, the changes to the automation preferences aren't restored to their pre-guzzlr settings.  Normally I have no pre-adventure script set but when guzzlr.ash aborts it leaves the autoscend pre-adventure script in place.  If the script exits normally this doesn't happen.

`Updating inventory...
Taking a Gold delivery
Encounter:     Guzzlr Client Selection
Submitting option 3 for choice 1412
Searching     for "bottle of gin"...
Search complete.
afterAdventureScript     => scripts/autoscend/auto_post_adv.ash
betweenBattleScript =>     scripts/autoscend/auto_pre_adv.ash
failed to unlock     the zone [The Fungal Nethers]
Stack trace:
  at     guzzlr_deliverLoop (guzzlr.ash:713)
  at guzzlr_deliver (guzzlr.ash:774)
  at     guzzlr_aftercore (guzzlr.ash:791)
  at main (guzzlr.ash:842)
printStackOnAbort     => false
afterAdventureScript => scripts\BestBetweenBattle.ash
breakableHandling     => 1
choiceAdventureScript =>
currentMood => default
maximizerCombinationLimit     => 200000
promptAboutCrafting => 1`

**Comment by taltamir** [comment]
thanks for letting me know. fixed
