### ISSUE TITLE
Unhandled choiceAdventure1341

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#34]
`[1969] The Overgrown Lot
Encounter: A Pound of Cure
Manual control requested for choice #1341
choice 1: Transfuse the pygmy blood (cure patient)
Click here to continue in the relay browser.

Stack trace:
  at guzzlr_deliverLoop (guzzlr.ash:750)
  at guzzlr_deliver (guzzlr.ash:774)
  at guzzlr_aftercore (guzzlr.ash:791)
  at main (guzzlr.ash:842)
printStackOnAbort => false
afterAdventureScript => scripts\BestBetweenBattle.ash
breakableHandling => 1
choiceAdventureScript =>
currentMood => default
maximizerCombinationLimit => 200000
promptAboutCrafting => 1`

**Comment by taltamir** [comment]
is it possible to encounter this if you do not have the cure item?

Looking at wiki https://kol.coldfront.net/thekolwiki/index.php/A_Pound_of_Cure
as well as your log I get the impression that the only option is choice 1. this makes it very easy to implement, as we just need to always click 1 without checks. Implemented it this way. let me know if this works or not.

**Comment by magus-prime** [comment]
Might as well mark it as fixed.  In several weeks of running your script I haven't encountered this issue before.
