### ISSUE TITLE
Disabling Bronze deliveries causes stack dump after completing last gold delivery

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#4]
I had set the script to take no Bronze deliveries and after completing three gold and one platinum deliveries generated a stack dump.

`Failed to start guzzlr quest for some reason
Stack trace:
  at guzzlr_deliverLoop (guzzlr.ash:365)
  at guzzlr_deliver (guzzlr.ash:469)
  at guzzlr_aftercore (guzzlr.ash:486)
  at main (guzzlr.ash:537)
printStackOnAbort => false
breakableHandling => 1
choiceAdventureScript => scripts\CounterChecker.ash
promptAboutCrafting => 1

Current settings for guzzlr:
guzzlr_deliverBronze = false
guzzlr_maxMeatCostBronze = 5000
guzzlr_deliverGold = true
guzzlr_maxMeatCostGold = 10000
guzzlr_deliverPlatinum = true
^Platinum will not be taken if you already used your 1 per day abandon
guzzlr_maxMeatCostPlatinum = 15000
^The maximum allowed price for cold wad and if needed a dayticket or access items
guzzlr_abandonTooExpensive = true
^When true will automatically abandon deliveries that are too expensive. When false will abort instead
guzzlr_deliverInrun = false
^Set to false to disable doing deliveries during a run
guzzlr_treatCasualAsAftercore = false
guzzlr_treatPostroninAsAftercore = true
guzzlr_abandonPlatinumForcedAftercore = false
^Override all other settings for the purpose of starting the day by taking a platinum delivery and immediately aborting it
guzzlr_abandonPlatinumForcedInrun = false
^Override all other settings for the purpose of starting the day by taking a platinum delivery and immediately aborting it`

**Comment by taltamir** [comment]
fixed
