### ISSUE TITLE
When autoscend is installed via git checkout this script errors on on svn update

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#42]
Just an FYI.  If autoscend, or any of the, github hosted, dependencies of ttpack are installed via git checkout then running svn update on ttpack errors out.

For now I've commented out the autoscend entry in my copy of dependencies.txt.

**Comment by taltamir** [comment]
Oh, thank you. I haven't looked at it in a while. Nice to see they finally implemented the git checkout.

**Comment by taltamir** [comment]
fixed.
thank you for the notification.

I added a manifest so it will now install correctly using
```
git checkout https://github.com/taltamir/ttpack.git
```
and also I cleared all git dependencies from this project. instead instructing the user to manually install them as necessary.

You should make sure to use `svn delete ttpack` and on any dependency this broke. as well as `git delete`. then reinstall them. Sorry about the mess there, hopefully the transition from svn checkout to git checkout doesn't have any more bumps along the way
