### ISSUE TITLE
Feature request - better logic for choosing platinum drinks

### ISSUE THREAD

**Issue by magus-prime** [taltamir/ttpack#5]
The script is set to only make Ghiaccio Coladas for the platinum drink.

I had a Buttery Boy, and over 500 dishes of clarified butter, in inventory but the script chose to use a cold wad, of which I had only 10, to make a Ghiaccio Colada.

Would you entertain the idea of either cost-based logic for choosing which drink to make or to allow user choice via a variable?

**Comment by taltamir** [comment]
At the moment it is hardcoded to use a cold wad. But cost based determination sounds like an improvement.

**Comment by taltamir** [comment]
fixed
