### ISSUE TITLE
add doing the pirate quest if needed and also unlock the other pirate zones

### ISSUE THREAD

**Issue by taltamir** [taltamir/ttpack#7]
add doing the pirate quest if needed for guzzlr quest.
and possibly hunting for swordfish NC to unlock belowdecks
with an option to abort instead

also auto equip fledges

**Comment by taltamir** [comment]
done 46a14929047a9f65472ee4a183b07f0f9b8f1923

**Comment by magus-prime** [comment]
WIth Mafia r20195 I the script tried to do a delivery in Belowdecks.  I tried the new option to allowPirateQuest and it failed with the following:

`> set guzzlr_allowPirateQuest = true

guzzlr_allowPirateQuest     => true

> guzzlr 50

printStackOnAbort     => true
promptAboutCrafting => 0
breakableHandling => 4
choiceAdventureScript     => scripts/autoscend/auto_choice_adv.ash
currentMood => apathetic
[INFO]     - Findin' the Cap'n
[INFO] - Equipping     eyepatch to slot hat
[INFO] - Equipping     swashbuckling pants to slot pants
[INFO] -     Equipping stuffed shoulder parrot to slot acc3
nextAdventure =>     Barrrney's Barrr

Restoring HP! Currently at     1214 of 2694 HP, 172 of 1781 MP, current meat: 902726766 ... Target HP =     2560.
Restoring MP! Currently at 1214 of     2694 HP, 172 of 1781 MP, current meat: 902726766 ... Target MP = 373.
Get     thee to a nunnery!
You gain 1,000 hit points
You gain 1,000 Mojo     Points
Casting Cannelloni Cocoon 1 times...
You gain 480 hit points
Cannelloni     Cocoon was successfully cast.

Visit to Island: Barrrney's Barrr in     progress...
You can't get to that area.

[INFO]     - Findin' the Cap'n
[INFO] - Equipping     eyepatch to slot hat
[INFO] - Equipping     swashbuckling pants to slot pants
[INFO] -     Equipping stuffed shoulder parrot to slot acc3

Visit to     Island: Barrrney's Barrr in progress...
You can't get     to that area.

[INFO] - Findin' the Cap'n
[INFO]     - Equipping eyepatch to slot hat
[INFO] -     Equipping swashbuckling pants to slot pants
[INFO]     - Equipping stuffed shoulder parrot to slot acc3`

This is in aftercore and all parts of the Swashbuckling Getup are in inventory.  After manually equiping the outfit I reran the script and it was able to adventure in the Barr and got the the Captain.

The script then got the map to the crab and the treasure but then maximized for Guzzlr deliveries.  That unequipped the Swashbuckling Getup which made it impossible to adventure in the Barr to continue with the quest to open the F'csle.

At this point there there aren't enough insults to continue even if wearing the outfit.  Only a 7.4% chance.

Here's the session log:  
[Arbos_20200618.txt](https://github.com/taltamir/ttpack/files/4798260/Arbos_20200618.txt)
